osx_instance:
  image: catalina-xcode

task:
  name: test_on_osx
  env:
    MPLBACKEN: Agg
    api_key: ENCRYPTED[!432a349969ff43e2d08fa1f291b3ef0296904b14240c6eeafd7364e91f762519e6f95a5693633a341d3963ba84b84c9a!]
    matrix:
      - PYENV: 3.6
      - PYENV: 3.7
  install_conda_script:
    - echo $SHELL
    - echo $api_key
    - brew update
    - brew cask install miniconda
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda init bash
  conda_env_script:
    - conda create -n tests python=${PYENV}
    - conda env update -n tests -f travis/osx_env.yml
    - source /Users/anka/.bash_profile
    - conda activate tests
    - python --version
    - python -c "import numpy; print('numpy %s' % numpy.__version__)"
    - python -c "import scipy; print('scipy %s' % scipy.__version__)"
    - python -c "import pandas; print('pandas %s' % pandas.__version__)"
    - python -c "import torch; print('pytorch %s' % torch.__version__)"
    - python -c "import pymatgen; print('pymatgen %s' % pymatgen.__version__)"
    - python -c "import rdkit; print('rdkit %s' % rdkit.__version__)"
    - python -c "from rdkit import Chem; print(Chem)"
  test_script:
    - echo "Test with pytest"
    - source /Users/anka/.bash_profile
    - conda activate tests
    - pip install -e .
    - pytest tests