# we don't use travis python virtualenv
language: python
virtualenv:
  system_site_packages: true

# shallow clone
git:
  depth: 3

matrix:
    include:
        - os: linux
          dist: trusty  # use ubuntu 14.04lts
          sudo: false  #  runs each build in a container on a shared host via Docker
          env: PYENV=py35
        - os: linux
          dist: trusty
          sudo: false
          env: PYENV=py36
        - os: linux
          dist: trusty
          sudo: false
          env: PYENV=py37
        - os: osx
          language: generic
          env: PYENV=py35
        - os: osx
          language: generic
          env: PYENV=py36
        - os: osx
          language: generic
          env: PYENV=py37

before_install:
  - source travis/before_install.sh

install:
  - pip install -e .

script:
  - pytest

deploy:
  provider: pypi
  user: tsumina
  distributions: sdist bdist_wheel
  password:
    secure: rDSV7JKnhsiZ5Cdo9LXNDi7rPqmAcOT5B+xL2buhhlWeSbEmeA2MkiVCRIIiQESU7z1IF3Ds7nK7iwaf45xuBTrouteBE9OpQHGcCpXPMLhLOwSMNtOfCwAoLtD8B8r5wYjDfC6wMEkRVuRv+ZjZtchIOJHY01FDeh9VhShV62H1P5TGA2Rpp/7rJBMam2yyNbgVad/ttvvbgn0ZLHKlLOA1nX5pqFNCyf/ZCR0IGZcWeAUoNjGcXNBkVMyEnnMIW813QDJEW+64cO/NFJuRCRWCDlTFOAvtWSBMdw9Ndu72bpe1maGPsRUSD652PebdpKVcnHFbn3i4Lt2bKkULUwKFvinAj2w4ceMXcfwxaXy6VmoFVf3ZHsnYNtLKBBiR6XCToI9u61vYW++uZ46njV4Pz1sHU1+I3QJVGBszOTXM8lirljM/aQNLO+gDanEXQRyjQkMRK9CXshxONMXwWaZtzkj8fr7zNH/fF5uAVieZ+tE82RJyRv9Z+G29hYc3A+7YLi3k7CYAbPi10Ir9PXBph4LorWSGMy1IcmCw5GND9PwMB5/BYgjQMh5ulekxU0JX+5rjWLIlsH9RWvKrz9V1wBIahpfU4jBpDz52hATf7JpZjKgv9pOj+otZfcEEX4cS+R7BGZ5cOE1cae3GZln9xNAqyJso1Cx/IJXUwgE=
  on:
    tags: true