name: xepy36
channels:
  - defaults
  - pytorch
  - rdkit
dependencies:
  - python=3.6
  - pandas
  - seaborn
  - requests
  - rdkit=2019.03.2
  - plotly
  - scikit-learn
  - scipy
  - pytorch=1.1.0
  - pytest
  - pytest-cov
  - pylint
  - sphinx
  - sphinx_rtd_theme
  - jupyter
  - nbconvert!=5.4
  - pip
  - pip:
      - nbsphinx
      - Python-Deprecated
      - ruamel.yaml
      - pymatgen==2019.5.8
      - jupyterlab
      - pybtex
      - mordred
      - yapf
      - tqdm
